In [1]:
import pandas as pd
import os

In [2]:
results_folder = '../experiments/results/experiment_2'

In [3]:
files = os.listdir(results_folder)

In [4]:
metrics = [file for file in files if 'metrics' in file]
topics = [file for file in files if 'topics' in file]

In [5]:
metrics_data = pd.DataFrame()
for path in metrics:
    df = pd.read_csv(results_folder+'/'+path)
    print('-'*7)
    print('MEAN:\n', df.iloc[:,1:].mean())
    print('\nSTD:\n',df.iloc[:,1:].std())
    metrics_data = metrics_data.append(df, ignore_index=True)

-------
MEAN:
 npmi         0.008888
diversity    0.836364
wetc         0.708005
dtype: float64
STD:
 npmi         0.025105
diversity    0.029069
wetc         0.029005
dtype: float64
-------
MEAN:
 npmi        -0.071533
diversity    0.818286
wetc         0.678264
dtype: float64
STD:
 npmi         0.024278
diversity    0.022086
wetc         0.012869
dtype: float64

In [6]:
metrics_data

    Unnamed: 0      npmi  diversity      wetc
0            0 -0.049732   0.860000  0.680649
1            1  0.036557   0.828571  0.734304
2            2  0.029365   0.850000  0.669921
3            3  0.005893   0.800000  0.678465
4            4 -0.010106   0.855556  0.725981
5            5  0.009172   0.833333  0.735501
6            6  0.030936   0.857143  0.721264
7            7  0.022588   0.822222  0.747044
8            8  0.007821   0.781818  0.676044
9            9  0.006385   0.875000  0.710873
10           0 -0.080520   0.828571  0.673677
11           1 -0.070677   0.814286  0.672435
12           2 -0.064989   0.785714  0.673601
13           3 -0.083237   0.785714  0.679291
14           4 -0.113637   0.833333  0.666976
15           5 -0.041042   0.840000  0.682033
16           6 -0.030120   0.850000  0.660333
17           7 -0.067355   0.828571  0.674521
18           8 -0.067832   0.800000  0.700471
19           9 -0.095925   0.816667  0.699299